### your site title here

title: HyperBlogLog
baseurl: # name of the repository
email: b at bede dawt im



highlighter: rouge
markdown: kramdown
### exclude the instructions / write-up in the README.md


# Tracker
analytics:

# Comments
disqus-shortname:

gems: [jekyll-seo-tag, jekyll-paginate]
